"""Phase 3: Add analytics and achievements tables

Revision ID: 80f4a872598d
Revises: c33c5467cc8c
Create Date: 2026-06-26 15:13:54.748240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f4a872598d'
down_revision: Union[str, Sequence[str], None] = 'c33c5467cc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
