"""Phase 2: Add position, start_date, org_id, team_id to tasks

Revision ID: c33c5467cc8c
Revises: e191a5a9db7b
Create Date: 2026-06-26 15:04:11.622554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33c5467cc8c'
down_revision: Union[str, Sequence[str], None] = 'e191a5a9db7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'team_id')
    op.drop_column('tasks', 'organization_id')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'position')
    # ### end Alembic commands ###
