"""Add google auth fields

Revision ID: e4044aad287d
Revises: 710d0b037443
Create Date: 2026-06-26 18:02:41.995052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4044aad287d'
down_revision: Union[str, Sequence[str], None] = '710d0b037443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_task_id'), 'activity_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_reports_user_id'), 'ai_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_user_id'), 'ai_suggestions', ['user_id'], unique=False)
    op.create_index(op.f('ix_productivity_logs_date'), 'productivity_logs', ['date'], unique=False)
    op.create_index(op.f('ix_productivity_logs_user_id'), 'productivity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_archived'), 'tasks', ['archived'], unique=False)
    op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_archived'), table_name='tasks')
    op.drop_index(op.f('ix_productivity_logs_user_id'), table_name='productivity_logs')
    op.drop_index(op.f('ix_productivity_logs_date'), table_name='productivity_logs')
    op.drop_index(op.f('ix_ai_suggestions_user_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_reports_user_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_task_id'), table_name='activity_logs')
    # ### end Alembic commands ###
